# Ultralytics ðŸš€ AGPL-3.0 License - https://ultralytics.com/license

name: ðŸ› Bug Report
# title: " "
description: Problems with Ultralytics LLM Chatbot
labels: [bug, triage]
type: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting an Ultralytics ðŸ› Bug Report!

  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please search the [issues](https://github.com/ultralytics/llm/issues) to see if a similar bug report already exists.
      options:
        - label: >
            I have searched the Ultralytics [issues](https://github.com/ultralytics/llm/issues) and found no similar bug report.
          required: true

  - type: dropdown
    attributes:
      label: Component
      description: |
        Please select the component where you found the bug.
      multiple: true
      options:
        - "Chat Interface"
        - "API Integration"
        - "Streaming Responses"
        - "Message Actions (Copy/Like/Dislike/Regenerate)"
        - "Code Highlighting"
        - "Markdown Rendering"
        - "Mobile UI"
        - "Dark Mode"
        - "Search Functionality"
        - "Session Management"
        - "Performance"
        - "Other"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Bug
      description: Please provide as much information as possible. Copy and paste console output and error messages including the _full_ traceback. Use [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to format text, code and logs. If necessary, include screenshots for visual elements only. Providing detailed information will help us resolve the issue more efficiently.
      placeholder: |
        ðŸ’¡ ProTip! Include as much information as possible (logs, tracebacks, screenshots, etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Please provide your system information to help us diagnose the problem.
      placeholder: |
        Please include:
        - Browser (e.g., Chrome 120.0, Safari 17.2, Firefox 121.0)
        - OS (e.g., Ubuntu 20.04, macOS 13.5, Windows 11)
        - Device (e.g., Desktop, Mobile, Tablet)
        - Screen size (if UI issue)
        - Any relevant environment details

        Example:
        ```
        Browser: Chrome 120.0.6099.129
        OS: macOS 14.2
        Device: MacBook Pro M3
        Screen: 1920x1080
        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: >
        Provide detailed steps to reproduce the bug. Include the exact sequence of actions, messages sent, buttons clicked, etc.
      placeholder: |
        1. Open chatbot
        2. Send message "..."
        3. Click regenerate button
        4. Observe error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        (Optional) We encourage you to submit a [Pull Request](https://github.com/ultralytics/llm/pulls) (PR) to help improve Ultralytics software for everyone, especially if you have a good understanding of how to implement a fix or feature.
        See the Ultralytics [Contributing Guide](https://docs.ultralytics.com/help/contributing/) to get started.
      options:
        - label: Yes I'd like to help by submitting a PR!
